# EC2 instance variable

stack_name: "test"
state: "present"
region: "ap-southeast-2"
infra_version: "1.0"

# security_groups : for CF stack
# security_group_ids : for non CF
ec2:
  ami_id: "ami-f2df0090"
  instance_type: "t2.large"
  key_pair: "steven"
  iam_role: "S3FullAccess"
  vpc_subnet_id: "subnet-b37ccfd6"
  security_group_ids:
    - "sg-e4150b9d"
  assign_public_ip: "yes"
  tags:
    Name: "APM TEST"
    Type: "Application"
    Env: "TEST"
  volumes:
    - device_name: /dev/xvda
      volume_type: standard
      volume_size: 8
