#
# Create EC2 instance by CloudFormation
- name: Create EC2 Stack using Cloudformation
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "ap-southeast-2"
    disable_rollback: false
    template: "{{playbook_dir}}/roles/ec2-cf/files/ec2.yml"
    tags:
      InfraCodeVersion: "{{ infra_version }}"
      Environment: "{{ env_type }}"
      Colour: "{{ colour }}"
  register: stack