#
# Create EC2 instance by CloudFormation
- name: Create EC2 Stack using Cloudformation
  cloudformation:
    stack_name: "SampleEC2Stack"
    state: "present"
    region: "ap-southeast-2"
    disable_rollback: false
    template: "{{playbook_dir}}/roles/ec2-cf/files/ec2.yml"
    tags:
      InfraCodeVersion: "1111"
      Environment: "222"
      Colour: "Blue"
      Stack: "333"
  register: stack