# 모든 기본값은 group_vars에 있는것을 참조하도록 하고, 기본값을 Overwrite하려면, Playbook을 실행시킬때 파라미터로 넘기도록 한다.
# Create EC2 instance by CloudFormation
- name: Create EC2 Stack using Cloudformation
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "ap-southeast-2"
    disable_rollback: false
    template: "{{playbook_dir}}/roles/ec2-cf/files/ec2_template.yml"
    template_parameters:
      AmiId : "{{ ami_id }}"
      InstanceType: "{{ instance_type }}"
      SecurityGroup:
        "sg-87b7c3e1, sg-e9acd88f"
    tags:
      InfraCodeVersion: "{{ infra_version }}"
      Environment: "{{ env_type }}"
      Colour: "{{ colour }}"
  register: stack