#
# Create EC2 instance
- name: Create an EC2 instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ ec2.key_pair }}"
    image: "{{ ec2.ami_id }}"
    instance_type: "{{ ec2.instance_type }}"
    instance_profile_name: "{{ ec2.iam_role | default('') }}"
    group_id: "{{ ec2.security_group_ids }}"
    vpc_subnet_id: "{{ ec2.vpc_subnet_id }}"
    assign_public_ip: "{{ ec2.assign_public_ip | default('no') }}"
    private_ip: "{{ ec2.private_ip | default('') }}"
    wait: true
    instance_tags: |
          {
              "Name":"{{ ec2.tags.Name }}",
              "Type":"{{ ec2.tags.Type }}",
              "Environment":"{{ ec2.tags.Env }}"
          }
  register: ec2Instance

- debug:
    msg: "instance: {{ ec2Instance }}"

- name: Wait for the servers to appear on the network
  wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=180 state=started
  with_items: ec2Instance.instances

- name: Add server ip addresses to hosts group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: ec2Instance.instances


- name: Add the ervers to the load balancer
  local_action: ec2_elb
  args:
    instance_id: "{{ item.id }}"
    ec2_elbs: appian
    state: present
    region: "{{ region }}"
  with_items: ec2Instance.instances