#
# Create EC2 instance
- name: Create instances
  ec2:
    region: "{{ ec2.region }}"
    keypair: "{{ ec2.credentials }}"
    image: "{{ ec2.image }}"
    instance_type: "{{ ec2.instance_type }}"
    instance_profile_name: "{{ ec2.role | default('') }}"
    group_id: "{{ ec2.sg_id }}"
    vpc_subnet_id: "{{ ec2.subnet }}"
    assign_public_ip: "{{ ec2.public_ip | default('no') }}"
    private_ip: "{{ ec2.private_ip | default('') }}"
    wait: true
    instance_tags: |
          {
              "Name":"{{ ec2.tags.Name }}",
              "Type":"{{ ec2.tags.Type }}",
              "Environment":"{{ ec2.tags.Env }}"
          }
  register: ec2
