AWSTemplateFormatVersion: "2010-09-09"
Description: "Ec2 block device mapping"

Parameters:
  AmiId:
    Type: String
  InstanceType:
    Type: String
  SecurityGroup:
    Type: "List<AWS::EC2::SecurityGroup::Id>"


Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AmiId
      KeyName: "steven"
      SecurityGroupIds: !Ref SecurityGroup
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "io1"
            Iops: "200"
            DeleteOnTermination: "false"
            VolumeSize: "20"
        - DeviceName: "/dev/sdk"
          NoDevice: {}
